spring:
  application:
    name: msUsers-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      profile: test  
       
server:
  port: 0

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
 
            
      
      

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
     
springdoc:
  show-actuator: true