spring:
  application:
    name: ms-config-server
  cloud:
    config:
      server:
        enabled: true
        git:
          uri: https://github.com/AugustoMello09/vinhoja-config-server
          default-label: main
          search-paths:
          - 'vinhoja-cofig-server*'  

server:
  port: 8888
  
      
